name: med_rent
description: Flutter application to rent medical equipment

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  flutter_svg: ^1.1.6
  dots_indicator: ^2.1.0
  cupertino_icons: ^1.0.2
  firebase_core: ^2.4.1
  firebase_auth: ^4.2.5
  firebase_storage: ^11.0.10
  image_picker: ^0.8.4+8
#  flutter_slider_drawer: ^2.1.1
  cloud_firestore: ^4.3.1
  flutter_easyloading: ^3.0.3
  provider: ^6.0.2
  legacy_progress_dialog: ^0.1.2
  google_sign_in: ^5.2.4
  email_validator: ^2.0.1
  open_mail_app: ^0.4.4
  bottom_navy_bar: ^6.0.0
  fluid_bottom_nav_bar: ^1.3.0
  paginated_search_bar: ^1.1.2
  font_awesome_flutter: ^10.1.0




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.11.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/image/logo.png"



  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/image/
    - assets/illustrations/

      # fonts:
      #   - family: Schyler
      #     fonts:
      #       - asset: fonts/Schyler-Regular.ttf
      #       - asset: fonts/Schyler-Italic.ttf
      #         style: italic
      #   - family: Trajan Pro
      #     fonts:
      #       - asset: fonts/TrajanPro.ttf
    #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

